### ISSUE TITLE
Loading locales in getInitialProps won't work with Lingui

### ISSUE THREAD

**Issue by jstcki** [wereHamster/next-multi-locale#2]
… because getInitialProps will serialize return values to JSON (and lingui locales are compiled JS)

**Comment by wereHamster** [comment]
The function isn't returning the translations, it's only returning the locale identifier, ie. "en", "de", "fr". The actual translations are loaded in _app via next.js dynamic import.

**Comment by jstcki** [comment]
Ah yes! Sorry, I misread :D
